### ISSUE TITLE
Missing rom.bin and game.db

### ISSUE THREAD

**Issue by LukasHromadnik** [maximeplante/GBSwift#1]
Hello,

I'm planning to write my own emulator and during my research I found your repo. I tried to build it but there are two files missing - `rom.bin` and `game.db`.

Can you please provide them?

Thank you!

**Comment by maximeplante** [comment]
I cannot share those since rom.bin is the GameBoy rom and game.db is any game (currently testing with Tetris). You will need to find those online :)
